--- 
- hosts: all
  gather_facts: False
  become: true

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - hosts: all

    roles:
         - mysql
         - php
         - server
         - wordpress
